before:
  hooks:
  - make clean
  - go mod download
  - go mod vendor
builds:
- binary: emulator
  ldflags:
  - -w
  - -X github.com/vapor-ware/synse-sdk/sdk.BuildDate={{ .Date }}
  - -X github.com/vapor-ware/synse-sdk/sdk.GitCommit={{ .ShortCommit }}
  - -X github.com/vapor-ware/synse-sdk/sdk.GitTag={{ .Tag }}
  - -X github.com/vapor-ware/synse-sdk/sdk.GoVersion={{ .Env.GOVERSION }}
  - -X github.com/vapor-ware/synse-sdk/sdk.PluginVersion={{ .Version }}
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
dockers:
- dockerfile: Dockerfile
  image_templates:
  - 'vaporio/emulator-plugin:latest'
  - 'vaporio/emulator-plugin:{{ .Major }}'
  - 'vaporio/emulator-plugin:{{ .Major }}.{{ .Minor }}'
  - 'vaporio/emulator-plugin:{{ .Major }}.{{ .Minor }}.{{ .Patch }}'
  build_flag_templates:
  - "--label=org.label-schema.schema-version=1.0"
  - "--label=org.label-schema.vendor=Vapor IO"
  - "--label=org.label-schema.version={{ .Version }}"
  - "--label=org.label-schema.name={{ .ProjectName }}"
  - "--label=org.label-schema.build-date={{ .Date }}"
  - "--label=org.label-schema.vcs-ref={{ .ShortCommit }}"
  extra_files:
  - config.yml
  - config/device
  goos: linux
  goarch: amd64
  binaries:
    - emulator


